USE DATABASE SCE_EPM_DB;
USE WAREHOUSE SCE_EPM_WH;

INSERT INTO RAW.PDF_TEXT (NORMALIZED_FILENAME, PARSED_JSON, CONTENT, PARSE_STATUS)
SELECT
    inv.NORMALIZED_FILENAME,
    parsed,
    parsed:content::TEXT,
    CASE WHEN parsed:errorInformation IS NULL THEN 'OK'
         ELSE 'ERROR: ' || parsed:errorInformation::VARCHAR END
FROM (
    SELECT
        inv.NORMALIZED_FILENAME,
        SNOWFLAKE.CORTEX.PARSE_DOCUMENT(
            @SCE_EPM_DB.RAW.PDF_STAGE, inv.NORMALIZED_FILENAME, {'mode': 'OCR'}
        ) AS parsed
    FROM RAW.PDF_INVENTORY inv
    LEFT JOIN RAW.PDF_TEXT pt ON pt.NORMALIZED_FILENAME = inv.NORMALIZED_FILENAME
    WHERE pt.NORMALIZED_FILENAME IS NULL
) inv;
